### ISSUE TITLE
Polls stop responding after a few hours

### ISSUE THREAD

**Issue by matnad** [matnad/pollmaster#2]
Polls stop responding to reactions when they fall out of the bot cache (5000 messages).

Fix: Rewrite the on_reaction_add() / remove() functions with on_socket_raw_receive()

**Comment by matnad** [comment]
Rewrite is done and problem should be fixed.
Closing for now.

**Comment by ciber96** [comment]
Hey, this bug is still present in production.
![image](https://user-images.githubusercontent.com/9750850/52675018-234af380-2f04-11e9-9174-3d6c8d4552f5.png)
